apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
  namespace: mock-backends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-service
  template:
    metadata:
      labels:
        app: mock-service
    spec:
      containers:
      - name: mock-service
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mock-service
  namespace: mock-backends
spec:
  selector:
    app: mock-service
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mock-service-ingress
  namespace: mock-backends
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: mock.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mock-service
            port:
              number: 80 