FROM node:16-alpine

WORKDIR /app

# Install nodemon for development
RUN npm install -g nodemon

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose ports
EXPOSE 4000
EXPOSE 9229

# Start the application in development mode with hot-reloading
CMD ["npm", "run", "dev"] 