apiVersion: v1
kind: Service
metadata:
  name: erp-loadbalancer
  namespace: erp-system
  annotations:
    # K3d/Traefik-spezifische Annotationen
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "ERP_ROUTE"
spec:
  type: LoadBalancer
  ports:
  - name: dashboard
    port: 80
    targetPort: 80
    protocol: TCP
  - name: api
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: valeo-final-dashboard  # Standardmäßig auf das Dashboard routen
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-access-config
  namespace: erp-system
data:
  hosts: |
    127.0.0.1 erp.local
    127.0.0.1 api.erp.local
    127.0.0.1 dashboard.erp.local 