version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: neuroerp-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-secret}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis Service
  redis:
    image: redis:latest
    container_name: neuroerp-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: neuroerp-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-neuroerp}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend API Service
  backend:
    build:
      context: ../core/backend
      dockerfile: Dockerfile
    container_name: neuroerp-backend
    restart: always
    depends_on:
      - mongodb
      - redis
      - postgres
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-secret}@mongodb:27017
      - REDIS_URI=redis://redis:6379
      - POSTGRES_URI=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-secret}@postgres:5432/${POSTGRES_DB:-neuroerp}
    ports:
      - "3000:3000"

  # Frontend Service
  frontend:
    build:
      context: ../core/frontend
      dockerfile: Dockerfile
    container_name: neuroerp-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongodb_data:
  redis_data:
  postgres_data: 