deployment:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

ingressRoute:
  dashboard:
    enabled: true

# Setze den Service auf NodePort f端r unsere Testumgebung
service:
  enabled: true
  type: NodePort
  annotations: {}
  spec:
    ports:
      web:
        port: 80
        nodePort: 30080
        protocol: TCP
      websecure:
        port: 443
        nodePort: 30443
        protocol: TCP

# Dashboard-Konfiguration
dashboard:
  enabled: true
  domain: dashboard.traefik.test

# Entrypoints-Konfiguration
ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: false

# HTTP zu HTTPS Redirect 端ber Middleware
additionalArguments:
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  - "--log.level=INFO"
  - "--accesslog=true"
  - "--api.insecure=true"
  - "--providers.kubernetesingress.ingressclass=traefik"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"

# Metriken f端r Prometheus
metrics:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: false  # Deaktiviert, da Prometheus Operator nicht installiert ist

# Persistence f端r Zertifikate
persistence:
  enabled: false 