# Service für den Finance-Service
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: erp-system
  labels:
    app: finance-service
spec:
  selector:
    app: finance-service
  ports:
  - name: http
    port: 8007
    targetPort: 8007
  - name: metrics
    port: 8008
    targetPort: 8008
  type: ClusterIP 