apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
  namespace: erp-system
  labels:
    app: finance-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
      annotations:
        # Prometheus-Annotationen für Metrik-Scraping
        prometheus.io/scrape: "true"
        prometheus.io/port: "8007"
        prometheus.io/path: "/metrics"
        # Jaeger-Annotationen für Tracing
        jaeger.erp-system.svc.cluster.local/inject: "true"
        jaeger.erp-system.svc.cluster.local/service-name: "finance-service"
    spec:
      containers:
      - name: finance-service
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8008
          name: metrics
        env:
        # Umgebungsvariablen für Metriken
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PATH
          value: "/metrics"
        - name: METRICS_PORT
          value: "8007"
        # Umgebungsvariablen für Jaeger Tracing
        - name: JAEGER_AGENT_HOST
          value: "erp-jaeger-agent.erp-system.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: "const"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_SERVICE_NAME
          value: "finance-service"
        - name: ENABLE_TRACING
          value: "true"
        # Umgebungsvariablen für strukturiertes Logging
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.erp-system.svc.cluster.local:9200"
        - name: USE_ELASTICSEARCH
          value: "true"
        # Spezifische Umgebungsvariablen für den Finance-Service
        - name: DATEV_EXPORT_ENABLED
          value: "true"
        - name: TRANSACTION_CACHE_TTL
          value: "300"
        volumeMounts:
        # Volume für Metriken-Konfiguration
        - name: metrics-config
          mountPath: /app/config/metrics
          readOnly: true
        # Volume für Tracing-Konfiguration
        - name: tracing-config
          mountPath: /app/config/tracing
          readOnly: true
        # Health Probes für Kubernetes
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      # ConfigMap für Metriken
      - name: metrics-config
        configMap:
          name: finance-service-metrics-config
      # ConfigMap für Tracing
      - name: tracing-config
        configMap:
          name: finance-service-tracing-config 