apiVersion: apps/v1
kind: Deployment
metadata:
  name: beleg-service
  namespace: erp-system
  labels:
    app: beleg-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beleg-service
  template:
    metadata:
      labels:
        app: beleg-service
      annotations:
        # Prometheus-Annotationen für Metrik-Scraping
        prometheus.io/scrape: "true"
        prometheus.io/port: "8020"
        prometheus.io/path: "/metrics"
        # Jaeger-Annotationen für Tracing
        jaeger.erp-system.svc.cluster.local/inject: "true"
        jaeger.erp-system.svc.cluster.local/service-name: "beleg-service"
    spec:
      containers:
      - name: beleg-service
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8021
          name: metrics
        env:
        # Umgebungsvariablen für Metriken
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PATH
          value: "/metrics"
        - name: METRICS_PORT
          value: "8020"
        # Umgebungsvariablen für Jaeger Tracing
        - name: JAEGER_AGENT_HOST
          value: "erp-jaeger-agent.erp-system.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: "const"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_SERVICE_NAME
          value: "beleg-service"
        - name: ENABLE_TRACING
          value: "true"
        # Umgebungsvariablen für strukturiertes Logging
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.erp-system.svc.cluster.local:9200"
        - name: USE_ELASTICSEARCH
          value: "true"
        # Spezifische Umgebungsvariablen für den Beleg-Service
        - name: DOCUMENT_STORAGE_PATH
          value: "/app/data/documents"
        - name: OCR_ENABLED
          value: "true"
        - name: DOCUMENT_CACHE_TTL
          value: "300"
        volumeMounts:
        # Volume für Metriken-Konfiguration
        - name: metrics-config
          mountPath: /app/config/metrics
          readOnly: true
        # Volume für Tracing-Konfiguration
        - name: tracing-config
          mountPath: /app/config/tracing
          readOnly: true
        # Volume für Dokumente
        - name: document-storage
          mountPath: /app/data/documents
        # Health Probes für Kubernetes
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      # ConfigMap für Metriken
      - name: metrics-config
        configMap:
          name: beleg-service-metrics-config
      # ConfigMap für Tracing
      - name: tracing-config
        configMap:
          name: beleg-service-tracing-config
      # PersistentVolumeClaim für Dokumente
      - name: document-storage
        persistentVolumeClaim:
          claimName: beleg-service-docs-new 