# Kubernetes-Manifest für den Dokumentenmanagement-Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  namespace: erp-system
  labels:
    app: document-service
    component: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: document-service
        component: storage
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8070"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: document-service
        image: nginx:alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8070
          name: metrics
        env:
        - name: STORAGE_PATH
          value: "/data/documents"
        - name: DB_HOST
          value: "document-db"
        - name: MAX_UPLOAD_SIZE
          value: "50MB"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8080"
        - name: ENABLE_METRICS
          value: "true"
        - name: METRICS_PATH
          value: "/metrics"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: document-storage
          mountPath: /data/documents
        - name: metrics-config
          mountPath: /app/config/metrics
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
          successThreshold: 1
      volumes:
      - name: document-storage
        emptyDir: {}
      - name: metrics-config
        configMap:
          name: document-service-metrics-config
          optional: true
---
# Service für Document-Service
apiVersion: v1
kind: Service
metadata:
  name: document-service
  namespace: erp-system
  labels:
    app: document-service
spec:
  selector:
    app: document-service
  ports:
  - port: 8070
    targetPort: 8070
    name: metrics
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP 