# Kubernetes-Manifest für Jaeger All-in-One-Deployment
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: erp-system
  labels:
    app: jaeger
    component: tracing
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 10s
    exporters:
      jaeger:
        endpoint: jaeger:14250
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: erp-system
  labels:
    app: jaeger
    component: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
        component: tracing
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.41.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5775
          protocol: UDP
          name: zipkin-thrift
        - containerPort: 6831
          protocol: UDP
          name: compact
        - containerPort: 6832
          protocol: UDP
          name: binary
        - containerPort: 5778
          name: agent-http
        - containerPort: 16686
          name: query
        - containerPort: 14268
          name: c-http
        - containerPort: 14250
          name: c-grpc
        - containerPort: 9411
          name: zipkin
        env:
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: "9411"
        - name: MEMORY_MAX_TRACES
          value: "10000"
        - name: QUERY_BASE_PATH
          value: /jaeger
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 16686
          initialDelaySeconds: 15
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: erp-system
  labels:
    app: jaeger
    component: tracing
spec:
  selector:
    app: jaeger
  ports:
  - port: 5775
    targetPort: 5775
    protocol: UDP
    name: zipkin-thrift
  - port: 6831
    targetPort: 6831
    protocol: UDP
    name: compact
  - port: 6832
    targetPort: 6832
    protocol: UDP
    name: binary
  - port: 5778
    targetPort: 5778
    name: agent-http
  - port: 16686
    targetPort: 16686
    name: query
  - port: 14268
    targetPort: 14268
    name: c-http
  - port: 14250
    targetPort: 14250
    name: c-grpc
  - port: 9411
    targetPort: 9411
    name: zipkin
  type: ClusterIP 