# Kubernetes-Manifest für Service-Integration-Tests
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-tests
  namespace: erp-system
  labels:
    app: service-tests
    component: testing
data:
  test-services.sh: |
    #!/bin/sh
    echo "=== Service Integration Tests ==="
    echo "Testing connection to all services..."
    
    echo "\n--- Testing Frontend Service ---"
    curl -s -o /dev/null -w "Frontend Service: HTTP Status: %{http_code}\n" http://frontend:80

    echo "\n--- Testing Document Service ---"
    curl -s -o /dev/null -w "Document Service: HTTP Status: %{http_code}\n" http://document-service:80
    
    echo "\n--- Testing Finance Service ---"
    curl -s -o /dev/null -w "Finance Service: HTTP Status: %{http_code}\n" http://finance-service:80
    
    echo "\n--- Testing Observer Service ---"
    curl -s -o /dev/null -w "Observer Service: HTTP Status: %{http_code}\n" http://observer-service:8010
    
    echo "\n--- Testing Beleg Service ---"
    curl -s -o /dev/null -w "Beleg Service: HTTP Status: %{http_code}\n" http://beleg-service:8020
    
    echo "\n--- Testing Monitoring Services ---"
    curl -s -o /dev/null -w "Prometheus: HTTP Status: %{http_code}\n" http://prometheus:9090
    curl -s -o /dev/null -w "Alertmanager: HTTP Status: %{http_code}\n" http://alertmanager:9093
    curl -s -o /dev/null -w "Grafana: HTTP Status: %{http_code}\n" http://grafana:3000
    curl -s -o /dev/null -w "Jaeger: HTTP Status: %{http_code}\n" http://jaeger:16686
    
    echo "\n=== Service Integration Tests Complete ==="
---
apiVersion: v1
kind: Pod
metadata:
  name: service-tester
  namespace: erp-system
  labels:
    app: service-tester
    component: testing
spec:
  containers:
  - name: tester
    image: curlimages/curl:latest
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    - "-c"
    - "cp /scripts/test-services.sh /tmp/ && chmod +x /tmp/test-services.sh && /tmp/test-services.sh"
    volumeMounts:
    - name: test-scripts
      mountPath: /scripts
  restartPolicy: Never
  volumes:
  - name: test-scripts
    configMap:
      name: service-tests
      defaultMode: 0777 